--TRUNCATE TABLE MANTENIMIENTO
SELECT * FROM MANTENIMIENTO
GO
INSERT MANTENIMIENTO VALUES('ANTHONY', 'QUISPE CUBAS', 'HUMBERTO@HOTMAIL.COM', '000000000', 'A', NULL)
GO
UPDATE MANTENIMIENTO SET CORREO = 'HUMBERTO_21@LIVE.COM', FECHA_UPDATE = (DATEADD(HOUR, 3, GETDATE())) WHERE ID = 1
