-- TRUNCATE TABLE MANTENIMIENTO
SELECT * FROM MANTENIMIENTO
GO
INSERT MANTENIMIENTO VALUES('JEFRINSSON', 'FERNANDEZ CALDERON', 'DOBLEJOTA_4R@LIVE.COM', '959850401', 'A', NULL, NULL)

SELECT * FROM MANTENIMIENTO WHERE ID_WEB IS NULL